name: XcraftWorlds
main: me.umbreon.xcraftworlds.XcraftWorlds
version: ${pom.version}
authors: [Engelier, Voronwe, Salami555, Umbreon]
load: STARTUP
commands:
  gworld:
    description: Manage Worlds
    usage: /<command> help
permissions:
  XcraftGate.world.*:
    description: Access to all /gworld commands
    default: op
    children:
      XcraftGate.world: true
      XcraftGate.world.create: true
      XcraftGate.world.delete: true
      XcraftGate.world.warp: true
      XcraftGate.world.setborder: true
      XcraftGate.world.setcreaturelimit: true
      XcraftGate.world.pvp: true
      XcraftGate.world.weather: true
      XcraftGate.world.time: true
      XcraftGate.world.info: true
      XcraftGate.world.load: true
      XcraftGate.world.difficulty: true
      XcraftGate.world.gamemode: true
      XcraftGate.world.spawn: true
  XcraftGate.world:
    description: Basic access to /gworld
  XcraftGate.world.create:
    description: Access to /gworld create
  XcraftGate.world.delete:
    description: Access to /gworld delete
  XcraftGate.world.warp:
    description: Access to /gworld warp
  XcraftGate.world.setborder:
    description: Access to /gworld setborder
  XcraftGate.world.setcreaturelimit:
    description: Access to /gworld setcreaturelimit, /gworld allowanimals, /gworld allowmonsters, /gworld suppresshealthregain
  XcraftGate.world.pvp:
    description: Access to /gworld allowpvp
  XcraftGate.world.weather:
    description: Access to /gworld allowweatherchange, /gworld setweather
  XcraftGate.world.time:
    description: Access to /gworld settime, /gworld timefrozen
  XcraftGate.world.info:
    description: Access to /gworld info, /gworld list
  XcraftGate.world.load:
    description: Access to /gworld load, /gworld unload, /gworld setsticky, /gworld keepspawninmemory
  XcraftGate.world.difficulty:
    description: Access to /gworld setdifficulty, /gworld setannouncedeath
  XcraftGate.world.gamemode:
    description: Access to /gworld setgamemode, /gworld setgamerule, /gworld setloginmessage
  XcraftGate.world.spawn:
    description: Access to /gworld setspawn
  XcraftGate.world.npgamemodechange:
    description: Don't change player's gamemode on world change or login
